### ISSUE TITLE
Attribute Error: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by neilpanchal** [cysmith/neural-style-tf#10]
Hello,

I think I have all the dependencies in place, I can launch python (version 2.7) and successfully 
```python
import tensorflow as tf
import numpy as np
import scipy.io
import argparse
import struct
import time
import cv2
import os
```

However, when I try to launch the bash script, I get the following error:

```
Rendering stylized image. This may take a while...
Traceback (most recent call last):
  File "neural_style.py", line 839, in <module>
    main()
  File "neural_style.py", line 836, in main
    else: render_single_image()
  File "neural_style.py", line 799, in render_single_image
    content_img = get_content_image(args.content_img)
  File "neural_style.py", line 704, in get_content_image
    img = cv2.imread(path, cv2.IMREAD_COLOR).astype('float')
AttributeError: 'NoneType' object has no attribute 'astype'
```

Any ideas what could be going on?

**Comment by neilpanchal** [comment]
Ok - I found the problem. It was that I didn't have the correct name of the input image file. 

Perhaps, as a suggestion to check if the input image or the style image(s) exist or throw an exception. Let me see if I can do a PR.

**Comment by cysmith** [comment]
I added a check for incorrect filenames.  I've also confused a .jpg with a .png or whatever.

**Comment by monajalal** [comment]
I get the same error but I don't know how to solve it:
 x[batchCount, frameIndex, :, :, :] = cv2.imread(frameFile, mode).astype('float32')

Please have a look at http://stackoverflow.com/questions/41883722/xbatchcount-frameindex-cv2-imreadframefile-mode-astypefloat32 and suggest solutions

**Comment by cysmith** [comment]
Hi monajalal,

Can you post or email me the command you tried and the error message?

Cam

**Comment by HosnaCSE** [comment]
Hello,
I want to resize my input image. I try to use cv2 but it shows error like 
"AttributeError: 'Tensor' object has no attribute 'astype'"

I don't get any error at library function but could not understand why it shows error during execution. 

import tensorflow as tf
import numpy as np
import cv2
import scipy.misc
....................................................
sam_batch = inputs[:, :, :, 1]
sam_resize = cv2.resize(sam_batch.astype('float32'), dsize=(64, 8, 8))

Any kind of suggestion will be appreciated. 
Hosna
