### ISSUE TITLE
Computing optical flow, multithreading

### ISSUE THREAD

**Issue by Schwusch** [cysmith/neural-style-tf#13]
I love this project, but the optical flow preprocessing step for video is... time consuming.
I thought about adding a check if the system has the [Gnome Parallel](http://www.gnu.org/software/parallel/) package e.g. checking the output from:
```bash
which parallel
```
and if so running the following snippet from make-opt-flow.sh on multiple cores:
```bash
while true; do
  file1=$(printf "$filePattern" "$i")
  file2=$(printf "$filePattern" "$j")
  if [ -a $file2 ]; then
    if [ ! -f ${folderName}/forward_${i}_${j}.flo ]; then
      eval $flowCommandLine "$file1" "$file2" "${folderName}/forward_${i}_${j}.flo"
    fi
    if [ ! -f ${folderName}/backward_${j}_${i}.flo ]; then
      eval $flowCommandLine "$file2" "$file1" "${folderName}/backward_${j}_${i}.flo"
    fi
    ./consistencyChecker/consistencyChecker "${folderName}/backward_${j}_${i}.flo" "${folderName}/forward_${i}_${j}.flo" "${folderName}/reliable_${j}_${i}.txt"
    ./consistencyChecker/consistencyChecker "${folderName}/forward_${i}_${j}.flo" "${folderName}/backward_${j}_${i}.flo" "${folderName}/reliable_${i}_${j}.txt"
  else
    break
  fi
  i=$[$i +1]
  j=$[$j +1]
done
```
The only problem I see is how to only run as many jobs as there are cores at the same time, since I don't have a lot of experience with Bash or GNU parallel.

Do you think it seems like a good idea?

**Comment by cysmith** [comment]
Yeah computing the optical flow estimation and stylizing the frames is _**very**_ slow. The authors of the video paper used the optical flow estimation algorithms [DeepFlow](http://lear.inrialpes.fr/src/deepflow/), [EpicFlow](http://lear.inrialpes.fr/src/epicflow/), and [DeepMatching](http://lear.inrialpes.fr/src/deepmatching/). They support multi-threading and there is a GPU implementation of DeepMatching. I think we could try those to speed it up.
