### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by lflee** [cysmith/neural-style-tf#17]
Hi!

Total newbie here.

I run your code on WSL ( https://blogs.msdn.microsoft.com/wsl/ ) on Windows 10. I tried a few small size jpgs (width or height no more than 512), the processes completed successfully.

Then I tried some bigger images and set max_size to 4000. Then it failed to complete. Bash shows below, should it be the WSL's issue or your codes' issue?

f@device:/mnt/c/Users/f/Documents/cysmith/neural-style-tf$ python neural_style.py --content_img 0102.jpg --style_imgs 17.jpg 16.jpg 15.jpg --style_imgs_weights 0.4 0.3 0.3 --max_size 4000 --max_iterations 30 --verbose --device /cpu:0;

---- RENDERING SINGLE IMAGE ----

BUILDING VGG-19 NETWORK
loading model weights...
constructing layers...
LAYER GROUP 1
--conv1_1 | shape=(1, 1926, 2180, 64) | weights_shape=(3, 3, 3, 64)
--relu1_1 | shape=(1, 1926, 2180, 64) | bias_shape=(64,)
--conv1_2 | shape=(1, 1926, 2180, 64) | weights_shape=(3, 3, 64, 64)
--relu1_2 | shape=(1, 1926, 2180, 64) | bias_shape=(64,)
--pool1   | shape=(1, 963, 1090, 64)
LAYER GROUP 2
--conv2_1 | shape=(1, 963, 1090, 128) | weights_shape=(3, 3, 64, 128)
--relu2_1 | shape=(1, 963, 1090, 128) | bias_shape=(128,)
--conv2_2 | shape=(1, 963, 1090, 128) | weights_shape=(3, 3, 128, 128)
--relu2_2 | shape=(1, 963, 1090, 128) | bias_shape=(128,)
--pool2   | shape=(1, 482, 545, 128)
LAYER GROUP 3
--conv3_1 | shape=(1, 482, 545, 256) | weights_shape=(3, 3, 128, 256)
--relu3_1 | shape=(1, 482, 545, 256) | bias_shape=(256,)
--conv3_2 | shape=(1, 482, 545, 256) | weights_shape=(3, 3, 256, 256)
--relu3_2 | shape=(1, 482, 545, 256) | bias_shape=(256,)
--conv3_3 | shape=(1, 482, 545, 256) | weights_shape=(3, 3, 256, 256)
--relu3_3 | shape=(1, 482, 545, 256) | bias_shape=(256,)
--conv3_4 | shape=(1, 482, 545, 256) | weights_shape=(3, 3, 256, 256)
--relu3_4 | shape=(1, 482, 545, 256) | bias_shape=(256,)
--pool3   | shape=(1, 241, 273, 256)
LAYER GROUP 4
--conv4_1 | shape=(1, 241, 273, 512) | weights_shape=(3, 3, 256, 512)
--relu4_1 | shape=(1, 241, 273, 512) | bias_shape=(512,)
--conv4_2 | shape=(1, 241, 273, 512) | weights_shape=(3, 3, 512, 512)
--relu4_2 | shape=(1, 241, 273, 512) | bias_shape=(512,)
--conv4_3 | shape=(1, 241, 273, 512) | weights_shape=(3, 3, 512, 512)
--relu4_3 | shape=(1, 241, 273, 512) | bias_shape=(512,)
--conv4_4 | shape=(1, 241, 273, 512) | weights_shape=(3, 3, 512, 512)
--relu4_4 | shape=(1, 241, 273, 512) | bias_shape=(512,)
--pool4   | shape=(1, 121, 137, 512)
LAYER GROUP 5
--conv5_1 | shape=(1, 121, 137, 512) | weights_shape=(3, 3, 512, 512)
--relu5_1 | shape=(1, 121, 137, 512) | bias_shape=(512,)
--conv5_2 | shape=(1, 121, 137, 512) | weights_shape=(3, 3, 512, 512)
--relu5_2 | shape=(1, 121, 137, 512) | bias_shape=(512,)
--conv5_3 | shape=(1, 121, 137, 512) | weights_shape=(3, 3, 512, 512)
--relu5_3 | shape=(1, 121, 137, 512) | bias_shape=(512,)
--conv5_4 | shape=(1, 121, 137, 512) | weights_shape=(3, 3, 512, 512)
--relu5_4 | shape=(1, 121, 137, 512) | bias_shape=(512,)
--pool5   | shape=(1, 61, 69, 512)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by cysmith** [comment]
Hi,

I think you are trying to allocate too much memory. I would not try a 4000 pixel image on a CPU. The GPU is about 30x-40x faster than the CPU. For an image that size, using the CPU will take a very long time.

Cam

**Comment by cysmith** [comment]
Hi lflee,

I am unfamiliar with WSL but it seems you are trying to allocate too much memory. I will try a 4K image on my machine. Although, I would not recommend rendering a 4K image on the CPU. It will take a very long time.

Cam
