### ISSUE TITLE
Pareidolic command line example

### ISSUE THREAD

**Issue by bmaltais** [cysmith/neural-style-tf#2]
Hi. Great work by the way. Really appreciate it.

Could you provide an example of how you achieved pareidolic results? Not sure how it was done with all the different options.

Thank you in advance ;-)

**Comment by cysmith** [comment]
Hi bmaltais,

Try increasing `--max_iterations` to a high value (e.g. >2000), initializing from a noise image with `--init_image_type random`, and/or using a higher style weight with `--style_weight 1e5`.  Some textures converged better than others; I tried clouds and couldn't quite get an image I wanted.

Cam
