### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by beraybentesen** [cysmith/neural-style-tf#21]
Is it possible to train first then apply transfer for instant process ?

**Comment by rowjay** [comment]
The training has already been done in the [VGG-19 model](http://www.vlfeat.org/matconvnet/pretrained/). The processing in this is feature optimization. See this link in README.md: [Image Style Transfer Using Convolutional Neural Networks](http://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Gatys_Image_Style_Transfer_CVPR_2016_paper.pdf) by Leon A. Gatys, Alexander S. Ecker, Matthias Bethge. So an 'optimal' image is 'found' based on content from one and style of another.

This is just my basic understanding though. I suppose you could update weights and biases for the style/content mix and save the model state then restore for similar faster optimization of similar content or style (or both). Check out [this link](https://www.tensorflow.org/api_docs/python/tf/train/Saver) on TensorFlow api docs. 

I imagine this been done elsewhere. Can you post anything you find @beraybentesen ?

**Comment by MarcoForte** [comment]
It is not possible with this version of style transfer. You can find what you are looking for here https://github.com/lengstrom/fast-style-transfer
