### ISSUE TITLE
About Quick Neural style

### ISSUE THREAD

**Issue by dovanchan** [cysmith/neural-style-tf#25]
I have learned many things from your code! but I felt a little slowly when run your net in GPU gtx 1080(about 10 mins for one picture).
I heard that there are some network that can implement The fast Neural Style and get the nearly result。Can you introduce some new and great github code for me ??I wanna learn more about the Neural Style!~ Really Thanks for you coding!~~

**Comment by MarcoForte** [comment]
This might be what you are looking for https://github.com/lengstrom/fast-style-transfer

**Comment by dovanchan** [comment]
https://github.com/tensorflow/magenta/tree/master/magenta/models/image_stylization 

This us Google's New projet.How do you think about this? Can you find some another code which can train multiple style to one model and then quick feedforward~

**Comment by MarcoForte** [comment]
Yes the google project is an extension of the one I linked. 

This can transfer arbitrary style https://github.com/rtqichen/style-swap

**Comment by dovanchan** [comment]
yes,thanks.But I wanna show you a amazing website. https://dreamscopeapp.com/
this style transfer, just take 30s ,and you can upload any style whatever you choose.it still just spend just 30s!!!!   and the pic is really beautiful,  do you know how they did that?share me the code~~

**Comment by dovanchan** [comment]
I have tried many neural style transfer code,But I think the photo you generate is really beautiful ;but the only disadvantage is about the speed and it can not save the model for next content ;
So,can you recommend another github which can be faster and save model ( almost the same transfer  result with you )

**Comment by dovanchan** [comment]
use  gtx1080 ,about 500s to generate a picture.How about you?

**Comment by cysmith** [comment]
Please keep issues related to problems with this project. There isn't much I can do about the speed of TensorFlow.
