### ISSUE TITLE
How would you use multiple style images with their corresponding masks?

### ISSUE THREAD

**Issue by njordsir** [cysmith/neural-style-tf#26]
For cases when style image 's1.jpg' is to be used to stylize the regions marked by 'm1.jpg' and so on.

**Comment by cysmith** [comment]
`--style_imgs s1.jpg s2.jpg --style_mask_imgs m1.jpg m2.jpg`

You need a mask for each style image though.

**Comment by njordsir** [comment]
To recreate the last segmentation example as given in the Readme, I executed the following, which follows the pattern you mentioned above.

`python neural_style.py --content_img 02270.jpg --content_img_dir examples/segmentation --style_imgs okeffe_red_canna.jpg okeffe_iris.jpg --style_imgs_dir examples/segmentation --style_mask_imgs 02270_mask_face.jpg 02270_mask_face_inv.jpg --verbose --model_weights "/xx/imagenet-vgg-verydeep-19.mat" --optimizer adam --max_iterations 1000 --print_iterations 10`

(The png images were converted to jpg prior to use)

This is the associated metadata : 

 image_name: result
 content: 02270.jpg
 styles[0]: 1.0 * okeffe_red_canna.jpg
 style_masks[0]: 02270_mask_face.jpg
 style_masks[1]: 02270_mask_face_inv.jpg
 init_type: content
 content_weight: 5.0
 style_weight: 1000.0
 tv_weight: 0.001 
 content_layers: ['conv4_2']
 style_layers: ['relu1_1', 'relu2_1', 'relu3_1', 'relu4_1', 'relu5_1']
 optimizer_type: adam
 max_iterations: 1000
 max_image_size: 512

I am unable to upload result here. Only one style image is being used for stylization.

**Comment by cysmith** [comment]
Hi njordsir,

I think you need to add the flag --style_mask`. I should change to just check if the length of the style mask images is >0.

Cam

**Comment by njordsir** [comment]
Adding the `--style_mask` flag and setting the blending weights as `--style_imgs_weights 0.5 0.5` generated the desired result. 

Maybe the blending weights could be equally distributed among all style images instead of the current default of `1.0`, unless otherwise specified.

Thanks for the very well-written code and your help.
