### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by dovanchan** [cysmith/neural-style-tf#28]
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,64,512,482]
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Relu, Const_2)]]
	 [[Node: add_25/_25 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1305_add_25", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by cysmith** [comment]
Hi dovanchan,

Hmm. I have not seen this one before. Can you email me the command you used and the images? My email is on my profile.

Cam
