### ISSUE TITLE
 Effect of different layers of CNN

### ISSUE THREAD

**Issue by limitforever** [cysmith/neural-style-tf#44]
Hello,cysmith!
    In your code,I found that you defined the content network structure as CONTENT_LAYERS = 'con4_2', while the there are also other different desighed such as 'relu4_2' or ('relu4_2', 'relu5_2').
   So my question is : what are the differences among them?   
   I'll be appreciated if you could reply.

**Comment by cysmith** [comment]
Different authors seem to have different naming conventions. Some call the convolution and activation combined 'conv4_2' or 'relu4_2'. Others call the convolution 'conv4_2' and the activation 'relu4_2'. I did not notice any noticeable difference when using conv or relu layers.
