### ISSUE TITLE
Optical flow procedure

### ISSUE THREAD

**Issue by Sugarbank** [cysmith/neural-style-tf#47]
Hi mate, I'm a bit confused about the syntax for the /make-opt-flow.sh

Are you able to provide an example if my video frames are named eg.
Video_001
Video_002
Video_003
etc.

and are in a directory called /VideoFrames

just not sure how to adhear to this syntax request
./make-opt-flow <filePattern> <outputFolder> [<startNumber> [<stepSize>]]

        filePattern:    Filename pattern of the frames of the videos.
        outputFolder:   Output folder.
        startNumber:    The index of the first frame. Default: 1
        stepSize:       The step size to create long-term flow. Default: 1

Cheers, sorry if this is a dumb question.Thanks in advance:)
Legend

**Comment by sevagc** [comment]
Hi! Were you able to figure this out? Would love some insight if so!
