### ISSUE TITLE
Training the network

### ISSUE THREAD

**Issue by pranith246** [cysmith/neural-style-tf#55]
I wish to train the network. Where can I get the dataset? And how to train it?

**Comment by Passionate321** [comment]
[http://www.vlfeat.org/matconvnet/pretrained/#downloading-the-pre-trained-models](url)
download the 'imagenet-vgg-verydeep-19.mat'  from this link.

**Comment by pranith246** [comment]
But I want the images in their original form not in mat file. So is there any way I can get them?

**Comment by chamoulox** [comment]
Hello,

The network was created for ImageNet challenge (see [http://www.image-net.org/](here), you can download the datasets from Download page  I think (only educational or research purpose)

**Comment by cysmith** [comment]
There is no point to retraining VGG on ImageNet. You may want to do transfer learning where you train a model pre-trained on ImageNet for a different classification task. See [this](http://cs231n.github.io/transfer-learning/)

**Comment by pranith246** [comment]
Got that. Thank you!
