### ISSUE TITLE
#time for cpu v/s gpu

### ISSUE THREAD

**Issue by Passionate321** [cysmith/neural-style-tf#56]
If gpu is not activated, On cpu approx. how much time will it take to give the result for a single image as well as video?

**Comment by o76923** [comment]
That's not really something that anyone can really give a great answer to. It depends on specifics like how many cores your CPU has and how fast they are as well as what kind of graphics card you are comparing it to and if it has enough memory to hold the matrix.

Very roughly speaking, my experience is that the difference is 12ish seconds vs 3-7 minutes but my machine also does some pretty intense research so it's got hardware designed for this kind of thing.

**Comment by Passionate321** [comment]
okay , thanks!
