### ISSUE TITLE
ValueError: Shape (1, 512, 512, 64) must have rank 1

### ISSUE THREAD

**Issue by xinghedyc** [cysmith/neural-style-tf#6]
Hi， I got an error when running the example : 
"bash stylize_image.sh ./image_input/lion.jpg ./styles/starry-night.jpg"
error: 
Traceback (most recent call last):
  File "neural_style.py", line 839, in <module>
    main()
  File "neural_style.py", line 836, in main
    else: render_single_image()
  File "neural_style.py", line 805, in render_single_image
    stylize(content_img, style_imgs, init_img)
  File "neural_style.py", line 556, in stylize
    L_style = sum_style_losses(sess, net, style_imgs)
  File "neural_style.py", line 407, in sum_style_losses
    style_loss += style_layer_loss(a, x) * weight
  File "neural_style.py", line 355, in style_layer_loss
    A = gram_matrix(a, M, N)
  File "neural_style.py", line 361, in gram_matrix
    F = tf.reshape(x[0], (area, depth))
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/ops/array_ops.py", line 338, in _SliceHelper
    sliced = slice(tensor, indices, sizes)
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/ops/array_ops.py", line 388, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/ops/gen_array_ops.py", line 2001, in _slice
    name=name)
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/framework/ops.py", line 2312, in create_op
    set_shapes_for_outputs(ret)
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/framework/ops.py", line 1704, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/ops/array_ops.py", line 1510, in _SliceShape
    input_shape.assert_has_rank(ndims)
  File "/home/dyc/tensorflow-0.10.0rc0/_python_build/tensorflow/python/framework/tensor_shape.py", line 621, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (1, 512, 512, 64) must have rank 1

environment:cuda 8.0rc ,tensorflow 0.10rc ,python 2.7 
something wrong with these versions?
looking forward to your help!
thanks

**Comment by cysmith** [comment]
My setup is:
cuda 8.0
python 2.7.12
tensorflow 0.10.0rc

I'll look into this today...

**Comment by gtoderici** [comment]
FYI -- it's likely a cuda issue.

Try the following code. If you see any errors, it's likely a bad configuration of cuda/cuDNN. Notice the "correct" output below (in my case I have a Quadro + K40, but only the K40 is listed):

$ ipython
In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally

In [2]: tf.test.device_lib.list_local_devices()
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:05:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x21973b0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 1 with properties: 
name: Quadro K600
major: 3 minor: 0 memoryClockRate (GHz) 0.8755
pciBusID 0000:04:00.0
Total memory: 964.81MiB
Free memory: 460.50MiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 0 to device ordinal 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 1 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y N 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 1:   N Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:05:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1028] Ignoring gpu device (device: 1, name: Quadro K600, pci bus id: 0000:04:00.0) with Cuda multiprocessor count: 1. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
Out[2]: 
[name: "/cpu:0"
device_type: "CPU"
memory_limit: 268435456
bus_adjacency: BUS_ANY
incarnation: 4541115684887390268
,
 name: "/gpu:0"
device_type: "GPU"
memory_limit: 11323454260
incarnation: 7838963373212564962
physical_device_desc: "device: 0, name: Tesla K40c, pci bus id: 0000:05:00.0"
]

What fixed it for me (to get the above output), was:

$ sudo apt-get install nvidia-modprobe

(I'm assuming you're running on ubuntu)

**Comment by cysmith** [comment]
xinghedyc, did gtoderici's suggestion:
`$ sudo apt-get install nvidia-modprobe`
produce the correct output?  It does on my machine.

**Comment by krystophv** [comment]
I'm also getting the Shape(...) must have rank 1 error, raised with a similar stack trace (line 361 in gram_matrix being the last line before library code). I have checked python's ability to load tensorflow and do some simple examples, so I don't think it's a CUDA misconfiguration. 

Ubuntu 16.04
Tensorflow 0.9.0
OpenCV 2.14.3
CUDA 8.0
cuDNN 5.1
Python 2.7.12

**Comment by cysmith** [comment]
Can you try adding `x = tf.convert_to_tensor(x)` after line 406?  I'm not getting this error.  Since you're using tensorflow 0.9.0 it could have something to do with that.

**Comment by cysmith** [comment]
I'm not getting this error so I'm kind of shooting in the dark.
Try:
- adding line  `x = tf.convert_to_tensor(x)` around line 406
- changing line 361 from `F = tf.reshape(x[0], (area, depth))` to `F = tf.reshape(x, (area, depth))`

Please let me know by email (cysmith1010@gmail.com) if that works as soon as you can.

**Comment by krystophv** [comment]
Well, after dropping the comment I decided to go ahead and try compiling tensorflow at the latest stable release (0.10.0) and that seems to have solved the issue (potentially). It's actually gotten into the L-BFGS code where it was erroring out well before that previously. It hasn't successfully finished (and won't for a little while - 750M isn't the fastest GPU on the block), but I'm hopeful.

**Comment by cysmith** [comment]
So we're thinking this bug is related to differences between tensorflow builds 0.9.0, 0.10.0rc, and 0.10.0?

**Comment by krystophv** [comment]
Since that's all I changed and it seems to work, that's the inference I would make. I don't really have the knowledge set to be able to say with confidence that there's a fix for the issue between 0.9.0 and 0.10.0, but it seems to be working for me.

**Comment by cysmith** [comment]
Ok. I pushed the change of line 361 from `F = tf.reshape(x[0], (area, depth))` to `F = tf.reshape(x, (area, depth))`

**Comment by xinghedyc** [comment]
@cysmith thanks a lot, It works for me.
environment:
ubuntu16.04
cuda 8.0rc
tensorflow 0.10
cuDNN 5
python 2.7
