### ISSUE TITLE
Should I train every time?

### ISSUE THREAD

**Issue by Heidisnaps** [cysmith/neural-style-tf#65]
Should I train every time?
For example, if I train Van Gogh style once.
If I want to Lion.jpg, rabbit.jpg to combine pictures in Van Gogh style,
Do I have to train my photos into neural-style-tf every time?

In the classification problem, it is very fast when verifying after learning.
Should I train neural styles every time?

**Comment by cysmith** [comment]
Yeah unfortunately. The optimization is done per image pair.
