### ISSUE TITLE
command not found: --content_img

### ISSUE THREAD

**Issue by ghost** [cysmith/neural-style-tf#81]
I can run the bash script with custom images just fine but when I try to run the python script, even using the demo script in the README I get this error:

`
neural_style.py: error: argument --style_imgs is required
`
`
zsh: command not found: --content_img
`

**Comment by 4F2E4A2E** [comment]
Your zsh is misinterpreting the command. 

Check and ask zsh why this is happening and please report back. 

Until then just use a standard bash console / terminal.
