### ISSUE TITLE
Script/params to recreate sample images?

### ISSUE THREAD

**Issue by gmccaig** [cysmith/neural-style-tf#9]
After installing and trying the basic image stylization example, as follows:
**bash stylize_image.sh ./image_input/lion.jpg ./styles/starry-night.jpg**

I obtained an output image that is "roughly" as expected, but seems less faithful to the style (e.g. less-accurate looking brushstrokes in the lion's mane), and with more artifacts (checkerboard-looking patches). Here was my output:

![result](https://cloud.githubusercontent.com/assets/22965123/19572166/fa550512-96b5-11e6-893f-2b0f685a781c.png)

Question- Is this output what you expect from running the example command above?

Suggestion- May I suggest you provide example parameters for users to recreate the output examples you display (whether some or all).

This would help very much in validating that we have installed and executed the code correctly.

Cheers

**Comment by cysmith** [comment]
Hi gmccaig,

I'm pretty busy for the next few weeks so I don't think this will happen.  I can maybe find the "meta_data.txt" files for each image.  I'll probably just change the example or the default settings.

To get a better lion image, try increasing the style weight `--style_weight` and running the optimization for more iterations `max_iterations`.  I also get the image you posted, so you've installed everything correctly.  The style "kandinsky.jpg" gets a decent result with the default settings:

![lion_kandinsky_1](https://cloud.githubusercontent.com/assets/9257969/19572899/50f28fec-96c1-11e6-85f8-081a08443569.png)

Cam

**Comment by cysmith** [comment]
Hi gmccaig,

Thanks for posting about this.  I changed the `--style_weight` to 1e5 and this is the result:
![demo_lion](https://cloud.githubusercontent.com/assets/9257969/19573562/05ee6338-96c4-11e6-83c6-36bc09c00a3e.png)

If you also ran this for more iterations `--max_iterations` you would be able to create an image like the one of my page or even closer to the style.

Cam

**Comment by gmccaig** [comment]
Thanks for the info and examples, Cameron.
That really helps me, much appreciated.

best
Graeme

**Comment by cysmith** [comment]
Hi Graeme,

It was a good suggestion.  I appreciate it.

Cam
